from PyQt5 import QtCore, QtGui, QtWidgets
from myUI4 import Ui_Form
from myUI4 import Ui_MainWindow as UI4CAM
from myUI3 import Ui_MainWindow as UI3CAM
class Ui_MainWindow(object):
    def openNewWindow(self):
      if self.oneCam.isChecked():
        numberCam = 1
      if self.twoCam.isChecked():
        numberCam = 2
      if self.threeCam.isChecked():
        print('three')
        self.ui = UI3CAM()
      if self.fourCam.isChecked():
        print('four')
        self.ui = UI4CAM()
      # print(numberCam)
      self.window = QtWidgets.QWidget()
      self.ui.setupUi(self.window)
      self.MainWindow.hide()
      self.window.show()

    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.setMinimumSize(QtCore.QSize(640, 500))
        self.MainWindow.setMaximumSize(QtCore.QSize(640, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.MainWindow.setFont(font)
        self.MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MainWindow.setWindowOpacity(1.0)
        self.MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(250, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setItalic(True)
        self.create_btn.setFont(font)
        self.create_btn.setAutoFillBackground(False)
        self.create_btn.setAutoDefault(False)
        self.create_btn.setDefault(True)
        self.create_btn.setFlat(False)
        self.create_btn.setObjectName("create_btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 601, 121))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 601, 111))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 0, 101, 81))
        self.label_4.setAutoFillBackground(True)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("edabk.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 141, 91))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 240, 331, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 290, 531, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.oneCam = QtWidgets.QRadioButton(self.widget)
        self.oneCam.setObjectName("oneCam")
        self.horizontalLayout_4.addWidget(self.oneCam)
        self.twoCam = QtWidgets.QRadioButton(self.widget)
        self.twoCam.setObjectName("twoCam")
        self.horizontalLayout_4.addWidget(self.twoCam)
        self.threeCam = QtWidgets.QRadioButton(self.widget)
        self.threeCam.setObjectName("threeCam")
        self.horizontalLayout_4.addWidget(self.threeCam)
        self.fourCam = QtWidgets.QRadioButton(self.widget)
        self.fourCam.setObjectName("fourCam")
        self.horizontalLayout_4.addWidget(self.fourCam)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(150, 120, 431, 91))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.healthyCare = QtWidgets.QRadioButton(self.widget1)
        self.healthyCare.setObjectName("healthyCare")
        self.horizontalLayout_5.addWidget(self.healthyCare)
        self.security = QtWidgets.QRadioButton(self.widget1)
        self.security.setObjectName("security")
        self.horizontalLayout_5.addWidget(self.security)
        self.Retail = QtWidgets.QRadioButton(self.widget1)
        self.Retail.setObjectName("Retail")
        self.horizontalLayout_5.addWidget(self.Retail)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.education = QtWidgets.QRadioButton(self.widget1)
        self.education.setObjectName("education")
        self.horizontalLayout_3.addWidget(self.education)
        self.smartCity = QtWidgets.QRadioButton(self.widget1)
        self.smartCity.setObjectName("smartCity")
        self.horizontalLayout_3.addWidget(self.smartCity)
        self.household = QtWidgets.QRadioButton(self.widget1)
        self.household.setObjectName("household")
        self.horizontalLayout_3.addWidget(self.household)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self.MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self.MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.security.setChecked(True)
        self.healthyCare.setCheckable(False)
        self.Retail.setCheckable(False)
        self.education.setCheckable(False)
        self.smartCity.setCheckable(False)
        self.household.setCheckable(False)

        self.oneCam.setCheckable(False)
        self.twoCam.setCheckable(False)
        
        # self.fourCam.setChecked(True)


        self.create_btn.clicked.connect(self.openNewWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "EDABK IVA SOFTWARE"))
        self.label.setText(_translate("MainWindow", "IVA SETUP"))
        self.create_btn.setText(_translate("MainWindow", "CREATE IVA"))
        self.label_5.setText(_translate("MainWindow", "Area"))
        self.label_6.setText(_translate("MainWindow", "Number of IP Camera"))
        self.oneCam.setText(_translate("MainWindow", "1 IP Camera"))
        self.twoCam.setText(_translate("MainWindow", "2 IP Cameras"))
        self.threeCam.setText(_translate("MainWindow", "3 IP Cameras"))
        self.fourCam.setText(_translate("MainWindow", "4 IP Cameras"))
        self.healthyCare.setText(_translate("MainWindow", "Health Care"))
        self.security.setText(_translate("MainWindow", "Security"))
        self.Retail.setText(_translate("MainWindow", "Retail"))
        self.education.setText(_translate("MainWindow", "Education"))
        self.smartCity.setText(_translate("MainWindow", "Smart City"))
        self.household.setText(_translate("MainWindow", "Household"))


if __name__ == "__main__":
    import sys
    App = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(App.exec_())